- menu_name: "Services"

- name: "Embedded Product Design"
  url: "/emb-prod-design/"
  title: "Embedded Product Design"

- name: "Firmware Development"
  url: "/firmware-dev/"
  title: "Firmware Development"

- name: "Board Design"
  url: "/board-design/"
  title: "Board Design"

# Do not delete this entry, it's used by footer!!
- name: "Contact Us"
  url: "/contact-us/"
  title: "Contact Us"